### PR TITLE
make close-handshake more explicit

### PR DESCRIPTION
**Pull request by Kriechi**

### CODE REVIEW

**Comment by Lukasa** [comment]
@jeamland Again, I think this is reasonable, but I'd like you to take a look at it as you're more familiar with websockets than I.

**Comment by njsmith** [comment]
It's not really clear to me what this change is trying to do -- can you elaborate?

**Comment by Kriechi** [comment]
Sorry, this PR is a few months old - this is what I remember:

When working on wsproto support in mitmproxy (https://github.com/mitmproxy/mitmproxy/pull/2545) we experienced odd behaviour durning the closing handshake, i.e., the final "CLOSE" frame was not sent/received.
ref https://tools.ietf.org/html/rfc6455#section-1.4

This PR tries to make the closing-handshake state change more explicit:
After the other endpoint sends a close frame, we have to reply with a close frame. This means this frame must also be received on the other end before the socket can be closed for real.
I added a test which checks for the correct state changes and received / sent frames.

**Comment by Kriechi** [comment]
@njsmith care to take another look?
The most important bit here is https://github.com/python-hyper/wsproto/pull/50/files#diff-c1e7881f91e3084e60df36b88fe06842R45.
Previously wsproto did not complete the two-way close handshake, due to entering the CLOSED state too early. Now it is documented properly that the final CLOSE frame is emitted and needs to be sent to the other endpoint.

**Comment by mehaase** [comment]
This PR directly addresses the point of confusion that I raised in #64. It's a small patch that makes the closing behavior more intuitive. I am working on a Trio WebSocket library, and this behavior is more convenient and simplifies my implementation.

I'm not a member of python-hyper, but as an unofficial reviewer I give this patch two thumbs up. :+1: :+1:

**Comment by smurfix** [comment]
Please merge this PR. It makes sense (eminently so) and simplifies using the library, as it allows me to separate "normal closing" and "abnormal connection loss" handling much more cleanly.

**Comment by njsmith** [comment]
@mehaase @smurfix As you've no doubt noticed, wsproto is rather unmaintained right now... would either or both of you be interested in becoming maintainers? (I'm not sure whether I have the authority to just grant that unilaterally, but I'm pretty sure @jeamland and @Lukasa won't have any objections.)

**Comment by Kriechi** [comment]
@njsmith I'm one of the @mitmproxy devs and we rely on wsproto and hyper-h2 for our protocol stack. 

So I'm pretty interested  in keeping this project alive! I'm already part of the `Contributor` python-hyper organization. I would be happy to take over responsibilities - including pushing out new releases!

**Comment by smurfix** [comment]
I'd recommend adding @Kriechi and/or @mehaase; my time is spread fairly thinly already, so I'm reluctant to add yet another project to the iist.

**Comment by mehaase** [comment]
I am happy to join the project. I can help out as a reviewer since that seems to be a bottleneck.

**Pull request merged**
