### PR TITLE
add "+dev" suffix to version

### PR DESCRIPTION
**Pull request by belm0**
as done in other projects (trio, etc.)

release process would be to bump version and remove suffix for release, then restore the suffix

### CODE REVIEW

**Comment by Kriechi** [comment]
Thanks for the PR - this is definitely an important thing to discuss and improve .
I feel like we should keep things similar across all python-hyper projects... but I don't have a strong opinion either way.

@belm0 I think the `+dev` is not valid according to [PEP440](https://www.python.org/dev/peps/pep-0440/#development-release-separators) - any reasoning why you chose that?
@pgjones any release workflow ideas / opinions?

**Comment by njsmith** [comment]
There are a lot of different conventions for this. This is the one I use on my projects, and I guess @belm0 got it from me :-).

According to PEP 440, + suffixes are legal but cannot be uploaded to PyPI. The benefits of this approach are (a) clear distinction between official releases and development snapshots, (b) stupidly simple, no fancy tools needed, (c) no need to predict the future and guess what the next release will be called, the way you have to for `.dev` versions.

**Comment by belm0** [comment]
+1 for `-dev` or equivalent.

If I pip install from a project's git master (which in practice seems necessary now and then), when I do a pip --list I'd like to see versions follow conventions, including a proper dev suffix.
`+foo` is used for patches (borrowed from Debian version conventions). `-dev` etc. means it's an unreleased snapshot.

https://www.python.org/dev/peps/pep-0440/#development-release-separators
https://www.python.org/dev/peps/pep-0440/#local-version-segments

**Comment by belm0** [comment]
to summarize the two options:

1. advance version immediately upon release.  E.g. 0.1.0-dev released as 0.1.0 and follow up with bump on master to 0.2.0-dev
2. leave old version upon release.  E.g. 0.1.0+dev (not following the PEP since `+` means non-upstream patch) released as 0.2.0 and follow up with bump on master to 0.2.0+dev.

#2 has an advantage that you can't accidentally upload to pypi (due to `+`), and it may seem more natural to decide the release version number at release time

#1 is used on almost every project I've worked on in my career, follows the PEP, and nothing precludes you from actually decided on a different version at release time

**Comment by Kriechi** [comment]
> According to PEP 440, + suffixes are legal but cannot be uploaded to PyPI.

I think I actually like `+` more than the other solutions. Not having to decide the next release number BEFORE actually doing the release is a major advantage, and a neat thing I wish I'd had in other projects as well!

@belm0 I I understand PEP440 correctly, `0.1.0-dev` kinda assumes there will be a `0.1.0`. Or can you elaborate on your statement: *nothing precludes you from deciding on a different version number at release time*?

**Comment by belm0** [comment]
> Or can you elaborate on your statement: nothing precludes you from deciding on a different version number at release time?

I can cite examples from high profile projects such as the linux kernel, Lua, etc.  Yes, you spend months or years working on "2.3.0-dev", but at release time the maintainer announces "this version is so incredible that we've released it as 3.0.0.  Onward with 3.1.0-dev!".

**Comment by Kriechi** [comment]
Sure other projects and other ecosystems.
I can only speak from experience within the Python system - and managing version numbers, non-official releases etc. can be a major pain. Especially when version numbers / numbering schemes change. One thing to keep in mind: wsproto is a library, and as such other projects include us as dependency. As such we need to make sure to be a good citizen with semver and related ideas.
People who install from wsproto-git-master as `1.0.0-dev` and later want to install an official `0.99` might get into trouble... Thats my only concern.

Let's keep this PR open over the next 1-2 weeks, while @pgjones and I prepare for the next release.
I'm happy to adopt something along the lines proposed here - I just want to make sure we don't create problems a few months or releases down the road.

**Comment by belm0** [comment]
> Sure other projects and other ecosystems.

Isn't Python's described in the PEP, which took the side of bumping the version number in dev naming?

Having some safeguard in PyPi is great, but perhaps we could ask PyPi to additionally disallow package versions with a dev suffix, rather than abusing `+` which is clearly reserved for patches?

**Comment by pgjones** [comment]
I don't have a strong opinion on this, I typically just leave the version number in the branch as it is. If it is useful though, I'd prefer to copy @njsmith and set the current number to `0.12.0+dev`.

**Comment by Kriechi** [comment]
Thanks for the discussion and input on versioning schemes! 🎉 👍 
Let's use `+dev`, same as h11 and a few other projects.
Closed by dec56c045fc488f1031a831feb29a2995bd3a137

**Pull request closed without merging**
