### PR TITLE
replace ConnectionType with client_side bool

### PR DESCRIPTION
**Pull request by Kriechi**
This resembles the API of python-hyper/h2.
Open for discussion!

### CODE REVIEW

**Comment by Lukasa** [comment]
Tagging @njsmith and @jeamland.

So, I think there is value in unifying this with h2. However, I think that h2's API choice here is *worse* than h11's and wsproto's. Boolean mystery-meat parameters that wildly change behaviour are rarely a good idea, and it was definitely an error to use one here. I think the enum is a better approach. So I believe that this is an area where h2 should probably aim to move closer to wsproto rather than the other way around. But I want to see what my colleagues think here. :grin:

**Comment by jeamland** [comment]
I agree that Mystery Bool is bad. If I had to criticise the approach wsproto is taking it'd be that it's not consistent between WSConnection and places like FrameDecoder so I'd prefer to see the enum pushed into there rather than replaced with a boolean.

Just to expand: I dislike using the boolean because it forces a notion of `client` vs `not-client` or `server` vs `not-server` instead of naming it appropriately as `client` or `server`. Given part of the sans-io school of thought, as I see it, is an overarching desire for correctness this feels like the right thing to do.

**Comment by Kriechi** [comment]
Just to add one more thought:
My twisted mind always messes up and tries to question the "direction", e.g., `client` means this object is **acting as client**, or is this object **talking to a client**?

Maybe we can come of with a neat way of getting rid of this distinction entirely, e.g., only using `initiate` / `accept` terminology? But then how do we communicate masking and other client-specific options...

**Comment by njsmith** [comment]
h11's strategy for avoiding that confusion is to name the variable like `our_role=CLIENT`

**Comment by Kriechi** [comment]
I quite like `our_role=CLIENT`! 👍 
@Lukasa what do you think, does this sound like a reasonable change for hyper-h2 as well?

**Comment by Kriechi** [comment]
I updated the PR accordingly.
Feel free to squash the commits - but for reviewing purposes I kept them.

**Comment by Lukasa** [comment]
I feel like we had this discussion already. 😉 I like the name, but I don’t think it justifies the API churn.

**Pull request closed without merging**
