### PR TITLE
Allow WSConnection to be initialised with open state

### PR DESCRIPTION
**Pull request by ujjwal96**
This PR allows WSConnection objects to be initialised with OPEN state. This allows immediate data transfer which is useful for @mitmproxy which handles the handshake itself.
@Kriechi 
ref: #27

### CODE REVIEW

**Comment by Kriechi** [comment]
This PR was created as part of this years GSoC project of @ujjwal96 for @mitmproxy. The corresponding work-in-progress PR is [here](https://github.com/mitmproxy/mitmproxy/pull/2463). The API changes are sufficient so that we can use wsproto in mitmproxy.

We are open to any changes / alternative approaches, if you think it would be a better fit to the overall API design.

**Comment by njsmith** [comment]
I haven't thought this through, but would it make sense to have a version of the handshake code where the user provides the handshake text (like: "here's what you're *going* to send"), and then the Connection reads it directly to pull out the information it needs? This way we wouldn't have to expose the Extension objects, the user wouldn't have to replicate our Extension header parsing code, and we'd automatically be set up to handle any future changes like new extensions, subprotocol tracking, cookie handling, or whatever. (Not saying that we'll necessarily do any of that, but it might be nice to have the option.)

**Comment by ujjwal96** [comment]
@njsmith Can you please give some examples?

**Comment by njsmith** [comment]
@ujjwal96: that is generally the kind of approach I had in mind, yeah. (Probably it'd be better to make it a method rather than pass to `__init__`, but that's a detail.)

**Comment by njsmith** [comment]
And to be clear, I'm asking what you and others think about this, not saying that this is the right way :-)

**Comment by Kriechi** [comment]
How about: `conn = WSConnection.from_headers(handshake_headers)` with headers being a generic dict-like object. If something is unsupported, it could raise an exception.

**Comment by Kriechi** [comment]
Let's revisit this after #48, #49, #50, and #51 are discussed (and approved) with a fresh approach.

**Pull request closed without merging**
